const order = [
  "Head Accessory",
  "Glasses",
  "Mouth Accessory",
  "Hair",
  "Earring Upper",
  "Earring Lower",
  "Orbital Piercing",
  "Industrial Piercing",
  "Helix Piercing",
  "Tragus Piercing",
  "Snug Piercing",
  "Neck Accessory",
  "Clothes",
  "Chest Accessory",
  "Eye Accessory",
  "Eyes",
  "Eyes Base",
  "Eyelashes & Liner",
  "Eye Shadow",
  "Eyebrows",
  "Nose Accessory",
  "Under Eye Makeup",
  "Face Paint",
  "Blush",
  "Cheekbone",
  "Nose Piercing Right",
  "Nose Piercing Left",
  "Septum Piercing",
  "Monroe Piercing",
  "Medusa Piercing",
  "Madonna Piercing",
  "Labret Right",
  "Labret Left",
  "Labret Centre",
  "Lipstick",
  "Bridge Piercing",
  "Beauty Mark",
  "Forehead Tattoo",
  "Scalp Tattoo",
  "Head Side Tattoo",
  "Shoulder Tattoo",
  "Chest Tattoo",
  "Base",
  "Skin Tone",
  "Background",
];

export {order}